image:
  repository: localhost:5001/tenant-node-site
  tag: latest

env:
  TENANT_NAME: "user1"

ingress:
  host: user1.127.0.0.1.sslip.io
  tls:
    secretName: user1-tenant-tls

certificate:
  dnsNames:
    - user1.127.0.0.1.sslip.io

replicaCount: 2

serviceMonitor:
  enabled: true
